import random
from typing import Final, TypedDict

ACTIVITIES = {
    "rainy": [
        "Go to The Met. Don't forget to check out Washington Crossing the Deleware!",
        "Catch a movie. If it's Tuesday, tickets are cheaper, so you can get a blue razz ICEE.",
        "Read performatively at the largest Barnes and Nobles in the world in Union Square.",
        "Check out the Natural History Museum. The planeterium is pretty cool.",
        "Go to a dog cafe and make a new bestfriend!",
    ],
    "sunny": [
        "Take a walk around Central Park. Bring a blanket to catch a tan on the Great Lawn",
        "Go to the Bronx zoo. Check out the crocodiles or feed the birds!",
        "Walk the High Line and enjoy the fresh air.",
        "Ride bikes on Governors Island. The ferry is free.",
        "Catch a game at Yankee Stadium or Citi Field. Choose wisely.",
        "Go shopping in Soho!"
    ],
    "freezing": [
        "Stay home. This is not negotiable.",
        "Go to Chelsea Market, and try everything.",
        "It is soup weather. Go get a bowl of pho.",
        "Go on a tour to find the best hot chocolate in the city.",
        "Grand Central. Just walk around and pretend you're in a movie.",
    ],
    "hot": [
        "Take the Staten Island Ferry to see the Statue of Liberty. It has AC.",
        "Head over to Rockaway Beach. It's only an hour from the city!!!.",
        "Go get ice cream and eat it before it melts!",
        "Find a shady spot in Central Park and don't move.",
    ],
    "perfect": [
        "Go outside immediately. These days are very rare.",
        "Just go for a walk. No destination necessary.",
        "Grab dinner with friends. Sit outside, enjoy the breeze, and people watch.",
        "Sit in Washington Square park and people watch.",
        "Bring a speaker and some friends to Central Park.",
        "Ride a bike along the Brooklyn Bridge and check out the skyline."
    ],  
}
ACTIVITIES["cold"] = ACTIVITIES["freezing"]



restaurant_list = {
    "american": {
        1: "Carmine's",
        2: "Jacob's Pickles",
        3: "Nightly",
        4: "The Smith",
        5: "Bubby's",
        6: "Corner Bistro",
        7: "J.G. Melon",
        8: "The Odeon",
        9: "Minetta Tavern",
        10: "Veselka",
        11: "Red Rooster Harlem",
        12: "Dinosaur Bar-B-Que",
        13: "Shake Shack",
        14: "Jack's Wife Freda",
        15: "Sarabeth's",
        16: "The Capital Grille",
        17: "Keens Steakhouse",
        18: "Gallagher's Steakhouse",
        19: "Sparks Steak House",
        20: "Westville",
        21: "Di Fara Pizza",
        22: "Grimaldi's",
        23: "Joe's Pizza",
        24: "Two Boots Pizza",
        25: "The Breslin",
        26: "Charlie Bird",
        27: "The Polo Bar",
        28: "The Boathouse Central Park",
        29: "Freemans",
        30: "Market Table",
        31: "Cookshop",
        32: "The Spotted Pig",
        33: "Five Leaves",
        34: "Junior's",
        35: "Sylvia's",
        36: "Amy Ruth's",
        37: "Virgil's Real BBQ",
        38: "Hill Country Barbecue",
        39: "Mighty Quinn's BBQ",
        40: "Emily",
        41: "Diner (Brooklyn)",
        42: "Tom's Restaurant",
        43: "The Fat Radish",
        44: "Pearl Oyster Bar",
        45: "Mary's Fish Camp",
        46: "The Lambs Club",
        47: "Harry's Cafe & Steak",
        48: "Whitehall",
        49: "Balthazar",
        50: "The Waverly Inn",
    },
    "italian": {
        1: "Trattoria Dell'Arte",
        2: "L'Artusi",
        3: "Via Carota",
        4: "Don Angie",
        5: "Lupa Osteria Romana",
        6: "Tony's Di Napoli",
        7: "L'Amico",
        8: "Torrisi",
        9: "Parm",
        10: "Numero 28",
        11: "Emilio's Ballato",
        12: "Cipriani Downtown",
        13: "Il Mulino",
        14: "Patsy's",
        15: "La Masseria",
        16: "Frankies 457 Spuntino",
        17: "Rubirosa",
        18: "John's of Bleecker Street",
        19: "Juliana's",
        20: "Totonno's",
        21: "Il Buco",
        22: "Osteria Morini",
        23: "Basta Pasta",
        24: "Gradisca",
        25: "Cacio e Pepe",
        26: "Bar Pitti",
        27: "Lucali",
        28: "Sottocasa",
        29: "Motorino",
        30: "Kesté",
        31: "Ribalta",
        32: "L&B Spumoni Gardens",
        33: "Supper",
        34: "Rafele",
        35: "Locanda Verde",
        36: "San Matteo",
        37: "Il Buco Alimentari",
        38: "Otto Enoteca",
        39: "Corsino",
        40: "Zero Otto Nove",
        41: "Convivio",
        42: "Bianca",
        43: "Piccola Cucina",
        44: "Giano",
        45: "Bar Primi",
        46: "Caffe Palermo",
        47: "Sant Ambroeus",
        48: "Il Cortile",
        49: "Fiorini",
        50: "Scalini Fedeli",
    },
    "chinese": {
        1: "Nan Xiang Xiao Long Bao",
        2: "Joe's Shanghai",
        3: "Xi'an Famous Foods",
        4: "Golden Unicorn",
        5: "Nom Wah Tea Parlor",
        6: "Jing Fong",
        7: "Peking Duck House",
        8: "Shun Lee Palace",
        9: "Wo Hop",
        10: "Great N.Y. Noodletown",
        11: "New Green Bo",
        12: "Vanessa's Dumpling House",
        13: "Oriental Garden",
        14: "Ping's Seafood",
        15: "456 Shanghai Cuisine",
        16: "Excellent Dumpling House",
        17: "Grand Sichuan St. Marks",
        18: "Spicy Village",
        19: "RedFarm",
        20: "Congee Village",
        21: "Fuleen Seafood",
        22: "Big Wong King",
        23: "Spicy & Tasty",
        24: "Shanghai You Garden",
        25: "Asian Jewels Seafood",
        26: "Lam Zhou Handmade Noodle",
        27: "Dim Sum Go Go",
        28: "Wonton Garden",
        29: "New Chao Chow",
        30: "Imperial Palace",
        31: "Bo Ky Restaurant",
        32: "Canton Gourmet",
        33: "Sun Golden Island",
        34: "Excellent Pork Chop House",
        35: "Decoy",
        36: "Tang Pavilion",
        37: "Shanghai 21",
        38: "Empire Szechuan",
        39: "The Bao",
        40: "Prosperity Dumpling",
        41: "Tasty Hand-Pulled Noodles",
        42: "King 5 Noodle House",
        43: "Hop Kee",
        44: "Han Dynasty",
        45: "Wu Liang Ye",
        46: "Mala Project",
        47: "Legend Bar & Restaurant",
        48: "New York Noodle Town",
        49: "Mission Chinese Food",
        50: "Hutong",
    },"french": {
        1: "Bar Boulud",
        2: "Raoul's",
        3: "Buvette",
        4: "L'Express",
        5: "Pastis",
        6: "Café d'Alsace",
        7: "Lucien",
        8: "Le Gigot",
        9: "Orsay",
        10: "Nice Matin",
        11: "Le Charlot",
        12: "Bilboquet",
        13: "Claudette",
        14: "Quercy",
        15: "La Mangeoire",
        16: "La Sirène",
        17: "Jules Bistro",
        18: "Bobo",
        19: "Chez Josephine",
        20: "Cherche Midi",
        21: "Brasserie Ruhlmann",
        22: "Jubilee",
        23: "Le Veau d'Or",
        24: "Benoit",
        25: "Félix",
        26: "Montmartre",
        27: "Café Un Deux Trois",
        28: "Demarchelier",
        29: "La Bonne Soupe",
        30: "Café du Soleil",
        31: "Pierre Au Tunnel",
        32: "Tout Va Bien",
        33: "Tournesol",
        34: "Chez Napoleon",
        35: "Sel et Poivre",
        36: "Le Fond",
        37: "Joséphine",
        38: "Côte d'Azur",
        39: "Les Halles",
        40: "Brasserie 8½",
        41: "Casimir",
        42: "Le Pescadou",
        43: "DB Bistro Moderne",
        44: "Bouchon Bakery",
        45: "Pigalle",
        46: "Le Rivage",
        47: "Marseille",
        48: "Chez Laurence",
        49: "La Goulue",
        50: "Calliope",
    },"japanese": {
        1: "Totto Ramen",
        2: "Ippudo",
        3: "Ichiran",
        4: "Momofuku Noodle Bar",
        5: "Soba Nippon",
        6: "Sake Bar Hagi",
        7: "Yakitori Totto",
        8: "Robataya",
        9: "Hasaki",
        10: "Rai Rai Ken",
        11: "Minca",
        12: "Kenka",
        13: "Takahachi",
        14: "Soba Totto",
        15: "Tomoe Sushi",
        16: "Hatsuhana",
        17: "Sushi of Gari",
        18: "Sushi Ann",
        19: "Sakagura",
        20: "Tanoshi Sushi",
        21: "Sushi Yasaka",
        22: "Otafuku",
        23: "Ivan Ramen",
        24: "Hide-Chan Ramen",
        25: "Setagaya",
        26: "Cocoron",
        27: "Sobaya",
        28: "Curry-Ya",
        29: "Hakata TonTon",
        30: "EN Japanese Brasserie",
        31: "Momoya",
        32: "Kura",
        33: "Sapporo",
        34: "Menchanko-tei",
        35: "Sake Bar Decibel",
        36: "Ramen Lab",
        37: "Izakaya MEW",
        38: "Yopparai",
        39: "Blue Ribbon Sushi Brooklyn",
        40: "Sushi Go 55",
        41: "Lucky Cat",
        42: "Nakamura Ramen",
        43: "Momo Sushi Shack",
        44: "Kanoyama",
        45: "Zutto",
        46: "Ramen Ishida",
        47: "Donguri",
        48: "Natsumi",
        49: "Sushisamba",
        50: "Paowalla (Japanese fusion)",
    }, "mexican": {
        1: "Los Tacos No. 1",
        2: "Empellón Taqueria",
        3: "Tacombi",
        4: "Cafe el Portal",
        5: "Chavela's",
        6: "Los Mariscos",
        7: "Maya",
        8: "Rosa Mexicano",
        9: "Dos Caminos",
        10: "La Palapa",
        11: "Toloache",
        12: "El Toro Blanco",
        13: "Otto's Tacos",
        14: "La Esquina",
        15: "Cafe Habana",
        16: "Hecho en Dumbo",
        17: "Lupe's East L.A. Kitchen",
        18: "Taco Mix",
        19: "El Parador Cafe",
        20: "Tehuitzingo",
        21: "La Superior",
        22: "Tortilleria Nixtamal",
        23: "Oaxaca Taqueria",
        24: "Calexico",
        25: "La Contenta",
        26: "Javelina",
        27: "Agave",
        28: "Suenos",
        29: "Taqueria Tlaxcalli",
        30: "Tres Carnes",
        31: "Don Pepe",
        32: "Mexico 2000",
        33: "El Vez",
        34: "Mercado Little Spain",
        35: "El Charro",
        36: "El Molcajete",
        37: "El Rey del Taco",
        38: "Mi Espiguita",
        39: "Noche Mexicana",
        40: "La Nueva Rampa",
        41: "La Flor de Broadway",
        42: "Tulcingo del Valle",
        43: "El Aguila",
        44: "Los Portales",
        45: "El Nuevo Azteca",
        46: "Zarela",
        47: "Mama Mexico",
        48: "Zona Rosa",
        49: "Atla",
        50: "Pio Pio",
    }, "indian": {
        1: "Tamarind",
        2: "Brick Lane Curry House",
        3: "Curry in a Hurry",
        4: "Chola",
        5: "Dawat",
        6: "Benares",
        7: "Haveli",
        8: "Chennai Garden",
        9: "Dhaba",
        10: "Tulsi",
        11: "Saravana Bhavan",
        12: "Salaam Bombay",
        13: "Minar",
        14: "Mumbai Masala",
        15: "Clay Oven",
        16: "Diwan",
        17: "Jackson Diner",
        18: "Pongal",
        19: "Dosa Royale",
        20: "Hampton Chutney Co.",
        21: "Bhatti Indian Grill",
        22: "Awadh",
        23: "Utsav",
        24: "Kati Roll Company",
        25: "Banjara",
        26: "Babu Ji",
        27: "Adda Indian Canteen",
        28: "Indus Valley",
        29: "Haldi",
        30: "Spice Symphony",
        31: "Darbar",
        32: "Mughlai",
        33: "Bombay Masala",
        34: "Bukhara Grill",
        35: "Yuva",
        36: "Seva Indian Cuisine",
        37: "Moti Mahal Delux",
        38: "Maharaja",
        39: "Malai Marke",
        40: "Dhamaka",
        41: "Nirvana",
        42: "Amma",
        43: "Indian Dream",
        44: "Tandoor Palace",
        45: "Kabab Cafe",
        46: "Sapphire Indian Cuisine",
        47: "Mint Indian Bistro",
        48: "Baluchi's",
        49: "Rangoli",
        50: "Purnima",
    },   "Korean": {
        1: "Kang Ho Dong Baekjeong",
        2: "Jongro BBQ",
        3: "Madangsui",
        4: "Miss Korea BBQ",
        5: "Gaonnuri",
        6: "Han Bat",
        7: "Mandoo Bar",
        8: "Cho Dang Gol",
        9: "BCD Tofu House",
        10: "Bann",
        11: "Woorijip",
        12: "Do Hwa",
        13: "Pocha 32",
        14: "Sik Gaek",
        15: "Corner Place",
        16: "Tofu Village",
        17: "Myung Dong Jeong",
        18: "Seoul Garden",
        19: "Dok Suni",
        20: "Haenyeo",
        21: "Yoon Haeundae Galbi",
        22: "Gahm Mi Oak",
        23: "New York Kom Tang",
        24: "Kunjip",
        25: "Palace Korean Restaurant",
        26: "Iron Chef House",
        27: "Barn Joo",
        28: "Hobak",
        29: "Hanok",
        30: "Seoulsa",
        31: "Gang Nam Barbeque",
        32: "Maru Korean Cuisine",
        33: "Cheogajip",
        34: "Busan BBQ",
        35: "Korean Village Restaurant",
        36: "Arisu",
        37: "Samwon Garden",
        38: "Wonjo",
        39: "Shilla",
        40: "Jin Dal Lae",
        41: "Modum",
        42: "Stone Korean BBQ",
        43: "Chuncheon Dakgalbi",
        44: "Myeong Dong Kyoja",
        45: "Wang Korean BBQ",
        46: "Seorabol",
        47: "Pocha Seoul",
        48: "Goo Korean BBQ",
        49: "Jua",
        50: "Seoul Chicken",
    },
    "thai": {
        1: "Pok Pok NY",
        2: "Ugly Baby",
        3: "Pure Thai Cookhouse",
        4: "SriPraPhai",
        5: "Thai Market",
        6: "Somtum Der",
        7: "Ayada Thai",
        8: "Zabb Elee",
        9: "Larb Ubol",
        10: "Kao Soy",
        11: "Zaab Zaab",
        12: "Eim Khao Man Gai",
        13: "Arharn Thai",
        14: "Pongsri Thai",
        15: "Chao Thai",
        16: "Jaya Thai",
        17: "Land Thai Kitchen",
        18: "Lan Larb Noodle House",
        19: "Wondee Siam",
        20: "Rhong-Tiam",
        21: "Room Service Thai",
        22: "Jasmine Thai",
        23: "Thai Villa",
        24: "Spice Thai Cuisine",
        25: "Siam Orchid",
        26: "Bangkok Kitchen",
        27: "Lotus Garden Thai",
        28: "Thai Son",
        29: "Siam Inn",
        30: "Krua Thai",
        31: "Am Thai Bistro",
        32: "Bai Tong",
        33: "Sa Wooei",
        34: "Thai Café",
        35: "Thai Angel",
        36: "Pinto Garden",
        37: "Little Thai Kitchen",
        38: "Nisi Thai",
        39: "Thai Smile",
        40: "Thai Basil",
        41: "Thai Number One",
        42: "Funky Thai Kitchen",
        43: "Thai Corner",
        44: "Thai Kitchen NYC",
        45: "Thai Garden",
        46: "Osha Thai",
        47: "Thai Palace",
        48: "Thai House",
        49: "Thai Delight",
        50: "Bangkok Centre",
        51:"Lum Lum"
    }
}
    
def find_restaurant(cuisuine: str, hours: int | None = 12):
    c_list = ["american","italian","chinese","french","japanese","mexican","indian","korean","thai"]
    for c in c_list:
        if cuisuine.lower()[0:2]==c[0:3]:
            cuisuine = c
            break
    if cuisuine not in c_list:
        return "Google and ask it to generate one restaurant for this cuisine, we don't have a great choice of this yet oops."
    
    restaurant_id = random.randint(0, len(restaurant_list[cuisuine])) #randomize one restaurant_id for a specific cuisuine
    restaurant = restaurant_list[cuisuine][restaurant_id] #here's the generated restaurant
    return restaurant

def find_activity(weather: str) -> str:
    if weather.lower() not in ACTIVITIES:
        return f"'{weather}' is not valid. Try: rainy, sunny, freezing, cold, hot or perfect."
    return random.choice(ACTIVITIES[weather.lower()])

class Venue(TypedDict):
    name: str
    website: str

class NightlifeCategory(TypedDict):
    activity_type: str
    places: list[Venue]

class NightlifeRecommendation(Venue):
    vibe: str
    activity_type: str

NIGHTLIFE_OPTIONS: Final[dict[str, NightlifeCategory]] = {
    "dancing": {
        "activity_type": "nightclub",
        "places": [
            {"name": "House of Yes", "website": "https://www.houseofyes.org/"},
            {"name": "Marquee New York", "website": "https://marqueeny.com/"},
            {"name": "Nebula", "website": "https://www.nebulanewyork.com/"},
            {"name": "Elsewhere", "website": "https://www.elsewherebrooklyn.com/"},
        ],
    },
    "music and vibes": {
        "activity_type": "bar",
        "places": [
            {"name": "The Django", "website": "https://www.thedjangonyc.com/"},
            {"name": "Skinny Dennis", "website": "https://skinnydennisbrooklyn.com/"},
            {"name": "Bar Lunatico", "website": "http://www.barlunatico.com/"},
            {"name": "Nublu 151", "website": "https://nublu.net/nublu-151/"},
        ],
    },
    "singing": {
        "activity_type": "karaoke",
        "places": [
            {"name": "Planet Rose", "website": "https://planetrose.com/"},
            {"name": "Sing Sing Avenue A", "website": "https://www.singsingavea.com/"},
            {"name": "Space Karaoke Bar & Lounge", "website": "https://spacekaraokebar.com/"},
            {"name": "Karaoke City", "website": "https://www.karaokecityny.com/"},
        ],
    },
    "laughing": {
        "activity_type": "comedy club",
        "places": [
            {"name": "Comedy Cellar", "website": "https://www.comedycellar.com/"},
            {"name": "Gotham Comedy Club", "website": "https://www.gothamcomedyclub.com/"},
            {"name": "New York Comedy Club", "website": "https://newyorkcomedyclub.com/"},
            {"name": "The Stand", "website": "https://www.thestandnyc.com/"},
        ],
    },
}

VIBE_ALIASES: Final[dict[str, str]] = {
    "bar": "music and vibes",
    "club": "dancing",
    "clubbing": "dancing",
    "comedy": "laughing",
    "dance": "dancing",
    "dancing": "dancing",
    "karaoke": "singing",
    "laughing": "laughing",
    "music": "music and vibes",
    "music and vibes": "music and vibes",
    "nightclub": "dancing",
    "singing": "singing",
    "vibes": "music and vibes",
}

def _normalize_vibe(vibe: str) -> str:
    normalized_vibe = vibe.strip().lower().replace("-", " ").replace("_", " ")
    normalized_vibe = " ".join(normalized_vibe.split())

    if normalized_vibe not in VIBE_ALIASES:
        valid_vibes = ", ".join(sorted(NIGHTLIFE_OPTIONS))
        raise ValueError(
            f"Unsupported vibe '{vibe}'. Choose from: {valid_vibes}."
        )

    return VIBE_ALIASES[normalized_vibe]

def list_nightlife_places(vibe: str) -> list[Venue]:
    """Return NYC nightlife options for a given vibe."""
    normalized_vibe = _normalize_vibe(vibe)
    places = NIGHTLIFE_OPTIONS[normalized_vibe]["places"]
    return [place.copy() for place in places]

def find_nightlife_activity(vibe: str) -> NightlifeRecommendation:
    """Select and return one random NYC nightlife activity (as dict) that matches the vibe."""
    normalized_vibe = _normalize_vibe(vibe)
    activity = NIGHTLIFE_OPTIONS[normalized_vibe]
    venue = random.choice(activity["places"])

    return {
        "vibe": normalized_vibe,
        "activity_type": activity["activity_type"],
        "name": venue["name"],
        "website": venue["website"],
    }

class Excursion(TypedDict):
    name: str
    location: str
    website: str

class ExcursionCategory(TypedDict):
    excursion_type: str
    places: list[Excursion]

EXCURSION_OPTIONS: Final[dict[str, ExcursionCategory]] = {
    "nature": {
        "excursion_type": "nature",
        "places": [
            {
                "name": "Bear Mountain State Park",
                "location": "Bear Mountain, NY",
                "website": "https://parks.ny.gov/parks/13/details.aspx",
            },
            {
                "name": "Cold Spring & Breakneck Ridge",
                "location": "Breakneck Ridge Trailhead, Cold Spring, NY 10516",
                "website": "https://parks.ny.gov/parks/hudsonhighlands/details.aspx",
            },
            {
                "name": "Governors Island",
                "location": "10 South Street, Slip 7, New York, NY 10004",
                "website": "https://www.govisland.com/",
            },
            {
                "name": "QC NY Spa",
                "location": "112 Andes Road, New York, NY 10004",
                "website": "https://www.qcny.com/",
            },
            {
                "name": "Collective Retreats Governors Island",
                "location": "Governors Island, New York, NY 10004",
                "website": "https://www.collectiveretreats.com/retreat/governors-island/",
            },
            {
                "name": "Mohonk Preserve",
                "location": "3197 Route 44/55, Gardiner, NY 12525",
                "website": "https://www.mohonkpreserve.org/",
            },
            {
                "name": "Palisades Interstate Park",
                "location": "P.O. Box 155, Alpine, NJ 07620",
                "website": "https://njpalisades.org/",
            },
            {
                "name": "Jamaica Bay Wildlife Refuge",
                "location": "175-10 Cross Bay Boulevard, Queens, NY 11414",
                "website": "https://www.nps.gov/gate/index.htm",
            },
            {
                "name": "Storm King Art Center",
                "location": "New Windsor, NY",
                "website": "https://www.stormking.org/",
            },
        ],
    },
    "historic": {
        "excursion_type": "historic",
        "places": [
            {
                "name": "Dia Beacon",
                "location": "3 Beekman Street, Beacon, NY 12508",
                "website": "https://www.diaart.org/visit/visit-our-locations-sites/dia-beacon-beacon-united-states",
            },
            {
                "name": "Washington Irving's Sunnyside",
                "location": "West Sunnyside Lane, Tarrytown, NY",
                "website": "https://hudsonvalley.org/historic-sites/washington-irvings-sunnyside/",
            },
            {
                "name": "Lyndhurst Mansion",
                "location": "635 South Broadway, Tarrytown, NY 10591",
                "website": "https://lyndhurst.org/",
            },
            {
                "name": "Independence Hall",
                "location": "520 Chestnut Street, Philadelphia, PA 19106",
                "website": "https://www.nps.gov/inde/planyourvisit/independencehall.htm",
            },
            {
                "name": "Philadelphia Museum of Art",
                "location": "2600 Benjamin Franklin Parkway, Philadelphia, PA 19130",
                "website": "https://philamuseum.org/visit",
            },
            {
                "name": "Tenement Museum",
                "location": "103 Orchard Street, New York, NY 10002",
                "website": "https://www.tenement.org/",
            },
            {
                "name": "Save Ellis Island Hard Hat Tour",
                "location": "Ellis Island, New York Harbor, NY 10004",
                "website": "https://www.saveellisisland.org/tour/hard-hat-tours/page.html",
            },
            {
                "name": "Chateau Bloomberg",
                "location": "New York, NY",
                "website": "https://knowledge.kitchen/food-and-drink/ch%C3%A2teau-bloomberg/",
            },
            {
                "name": "Sleepy Hollow",
                "location": "Sleepy Hollow, NY",
                "website": "https://www.visitwestchesterny.com/",
            },
            {
                "name": "Kykuit Estate",
                "location": "Pocantico Hills, NY",
                "website": "https://www.rbf.org/",
            },
        ],
    },
    "coastal": {
        "excursion_type": "coastal",
        "places": [
            {
                "name": "Montauk Lighthouse",
                "location": "Montauk, NY",
                "website": "https://montaukhistoricalsociety.org/",
            },
            {
                "name": "Asbury Park Boardwalk",
                "location": "Asbury Park, NJ",
                "website": "https://www.apboardwalk.com/",
            },
            {
                "name": "New York Media Boat / Adventure Sightseeing",
                "location": "Chelsea Piers, Pier 59, New York, NY 10011",
                "website": "https://www.advsightseeing.com/",
            },
            {
                "name": "Secret Food Tours New York",
                "location": "Chinatown and Little Italy, Manhattan, NY",
                "website": "https://www.secretfoodtours.com/new-york/",
            },
        ],
    },
}

EXCURSION_ALIASES: Final[dict[str, str]] = {
    "beach": "coastal",
    "coastal": "coastal",
    "historic": "historic",
    "history": "historic",
    "nature": "nature",
    "outdoors": "nature",
}

def _normalize_excursion(category: str) -> str:
    key = " ".join(category.strip().lower().replace("-", " ").replace("_", " ").split())
    if key not in EXCURSION_ALIASES:
        raise ValueError(f"Unknown category '{category}'. Try: {', '.join(EXCURSION_OPTIONS)}")
    return EXCURSION_ALIASES[key]

def list_excursions(category: str) -> list[Excursion]:
    return [p.copy() for p in EXCURSION_OPTIONS[_normalize_excursion(category)]["places"]]


def find_excursion(category: str) -> Excursion:
    return random.choice(list_excursions(category))